export const coursePLaylist = [
  {
    id: 1,
    Toggle: false,
    Topic: 'section 1',
    Videos: [
      {
        id: 1.1,
        subTopics: 'Topic 1',
        VideoUrl: 'videos/Video-1.mp4',
        Status: false,
        thumbnail: 'image/thumbnail-1.png',
        description: '',
      },
      {
        id: 1.2,
        subTopics: 'Topic 2',
        VideoUrl: 'videos/video-2.mp4',
        Status: false,
        thumbnail: 'image/thumbnail-2.png',
        description: '',
      },
      {
        id: 1.3,
        subTopics: 'Topic 3',
        VideoUrl: 'videos/video-3.mp4',
        Status: false,
        thumbnail: 'image/thumbnail-3.png',
        description: '',
      },
    ],
  },
  {
    id: 2,
    Toggle: false,
    Topic: 'section 2',
    Videos: [
      {
        id: 2.1,
        subTopics: 'Topic 1',
        VideoUrl: 'https://www.youtube.com/watch?v=CNCwiaEuq2s',
        Status: false,
        thumbnail: 'image/thumbnail-3.png',
        description: '',
      },
      {
        id: 2.2,
        subTopics: 'Topic 2',
        VideoUrl: 'https://www.youtube.com/watch?v=CNCwiaEuq2s',
        Status: false,
        thumbnail: 'image/thumbnail-3.png',
        description: '',
      },
      {
        id: 2.3,
        subTopics: 'Topic 3',
        VideoUrl: 'https://www.youtube.com/watch?v=CNCwiaEuq2s',
        Status: false,
        thumbnail: 'image/thumbnail-3.png',
        description: '',
      },
    ],
  },
  {
    id: 3,
    Toggle: false,
    Topic: 'section 3',
    Videos: [
      {
        id: 3.1,
        subTopics: 'Topic 1',
        VideoUrl: 'https://www.youtube.com/watch?v=CNCwiaEuq2s',
        Status: false,
        thumbnail: 'image/thumbnail-3.png',
        description: '',
      },
      {
        id: 3.2,
        subTopics: 'Topic 2',
        VideoUrl: 'https://www.youtube.com/watch?v=zgSj6w3fBi4',
        Status: false,
        thumbnail: 'image/thumbnail-3.png',
        description: '',
      },
      {
        id: 3.3,
        subTopics: 'Topic 3',
        VideoUrl: 'https://www.youtube.com/watch?v=CNCwiaEuq2s',
        Status: false,
        thumbnail: 'image/thumbnail-3.png',
        description: '',
      },
    ],
  },
];
