export const COURSE_REPOSITORY = 'COURSE_REPOSITORY';
export const COURSE_IMAGE_REPOSITORY = 'COURSE_IMAGE_REPOSITORY';
export const COURSE_VIDEO_REPOSITORY = 'COURSE_VIDEO_REPOSITORY';
export const USER_COURSE_REPOSITORY='USER_COURSE_REPOSITORY';
